import type { PageKey, RoleKey, NavSection } from '@/data/vcontent';

export const APP_ROLE_META: Record<RoleKey, { label: string; title: string }> = {
  admin: { label: 'Admin', title: 'Quản trị hệ thống · Toàn quyền' },
  pm: { label: 'PM', title: 'Điều phối sản xuất' },
  specialist: { label: 'Specialist', title: 'Storyboard · Design · Voice · Edit' },
  qc: { label: 'QC', title: 'Kiểm soát chất lượng' },
  client: { label: 'Client', title: 'Cổng khách hàng' },
  client_director: { label: 'Client Director', title: 'Duyệt đơn nội bộ khách hàng' },
};

export const APP_PAGE_LABELS: Record<PageKey, string> = {
  profile: 'Hồ sơ cá nhân',
  guide: 'Cẩm nang hướng dẫn sử dụng',
  dashboard: 'Tổng quan điều hành',
  tracking: 'Theo dõi sản xuất',
  notifications: 'Thông báo',
  'client-orders': 'Danh sách đơn hàng',
  'client-new-order': 'Khởi tạo đơn hàng',
  'client-order-detail': 'Chi tiết đơn hàng',
  'client-products': 'Nhập yêu cầu sản phẩm',
  'client-delivery': 'Nghiệm thu',
  'client-payment': 'Thanh toán',
  'client-approvals': 'Duyệt đơn khách hàng',
  'producer-inbox': 'Đơn chờ rà soát',
  'order-pm-dashboard': 'Điều phối đơn hàng',
  'producer-launch': 'Đưa vào sản xuất',
  'producer-deliver': 'Bàn giao sản phẩm',
  'producer-invoice': 'Đề nghị thanh toán',
  'production-workflow': 'Luồng sản xuất',
  'schedule-setup': 'Thiết lập kế hoạch',
  'my-tasks': 'Công việc của tôi',
  smf01: 'SMF-01 Quản lý đầu vào',
  smf02: 'SMF-02 Quản lý storyboard',
  smf03: 'SMF-03 Quản lý thiết kế slide',
  smf04: 'SMF-04 Quản lý QC slide',
  smf05: 'SMF-05 Quản lý thu voice',
  smf06: 'SMF-06 Quản lý biên tập video',
  smf07: 'SMF-07 Quản lý QC video',
  smf08: 'SMF-08 Quản lý SCORM + Quiz',
  vsmf01: 'VSMF-01 Quản lý đầu vào',
  vsmf02: 'VSMF-02 Quản lý storyboard',
  vsmf03: 'VSMF-03 Quản lý thiết kế slide',
  vsmf04: 'VSMF-04 QC slide',
  vsmf05: 'VSMF-05 Thu voice',
  vsmf06: 'VSMF-06 Biên tập video',
  vsmf07: 'VSMF-07 QC video',
  gsmf01: 'GSMF-01 Yêu cầu khởi tạo',
  gsmf02: 'GSMF-02 Màn chạy thử game',
  gsmf03: 'GSMF-03 QC game',
  gsmf04: 'GSMF-04 Game hoàn chỉnh',
  'qc-criteria': 'Tiêu chí QC',
  'lecturer-question-bank': 'Bộ câu hỏi giảng viên',
  users: 'Người dùng',
  audit: 'Nhật ký kiểm tra',
  'archived-products': 'Sản phẩm lưu trữ',
};

export const APP_NAV_SECTIONS: NavSection[] = [
  {
    title: 'Tổng quan',
    items: [
      { key: 'dashboard', label: APP_PAGE_LABELS.dashboard, icon: 'DB' },
      { key: 'tracking', label: APP_PAGE_LABELS.tracking, icon: 'TD' },
      { key: 'notifications', label: APP_PAGE_LABELS.notifications, icon: 'TB' },
    ],
  },
  {
    title: 'Quản lý đơn hàng',
    tone: 'gold',
    items: [
      { key: 'client-orders', label: APP_PAGE_LABELS['client-orders'], icon: 'DH' },
      { key: 'client-new-order', label: APP_PAGE_LABELS['client-new-order'], icon: 'MO' },
      { key: 'producer-inbox', label: APP_PAGE_LABELS['producer-inbox'], icon: 'RS' },
      { key: 'order-pm-dashboard', label: APP_PAGE_LABELS['order-pm-dashboard'], icon: 'DP' },
      { key: 'producer-launch', label: APP_PAGE_LABELS['producer-launch'], icon: 'SX' },
      { key: 'producer-deliver', label: APP_PAGE_LABELS['producer-deliver'], icon: 'BG' },
      { key: 'producer-invoice', label: APP_PAGE_LABELS['producer-invoice'], icon: 'TT' },
    ],
  },
  {
    title: 'Kế hoạch sản xuất',
    items: [
      { key: 'production-workflow', label: APP_PAGE_LABELS['production-workflow'], icon: 'WF' },
      { key: 'schedule-setup', label: APP_PAGE_LABELS['schedule-setup'], icon: 'KH' },
      { key: 'my-tasks', label: APP_PAGE_LABELS['my-tasks'], icon: 'CV' },
    ],
  },
  {
    title: 'Module E-learning',
    tone: 'violet',
    items: [
      { key: 'smf01', label: APP_PAGE_LABELS.smf01, icon: '01' },
      { key: 'smf02', label: APP_PAGE_LABELS.smf02, icon: '02' },
      { key: 'smf03', label: APP_PAGE_LABELS.smf03, icon: '03' },
      { key: 'smf04', label: APP_PAGE_LABELS.smf04, icon: '04' },
      { key: 'smf05', label: APP_PAGE_LABELS.smf05, icon: '05' },
      { key: 'smf06', label: APP_PAGE_LABELS.smf06, icon: '06' },
      { key: 'smf07', label: APP_PAGE_LABELS.smf07, icon: '07' },
      { key: 'smf08', label: APP_PAGE_LABELS.smf08, icon: '08' },
    ],
  },
  {
    title: 'Module Video học liệu',
    tone: 'red',
    items: [
      { key: 'vsmf01', label: APP_PAGE_LABELS.vsmf01, icon: '01' },
      { key: 'vsmf02', label: APP_PAGE_LABELS.vsmf02, icon: '02' },
      { key: 'vsmf03', label: APP_PAGE_LABELS.vsmf03, icon: '03' },
      { key: 'vsmf04', label: APP_PAGE_LABELS.vsmf04, icon: '04' },
      { key: 'vsmf05', label: APP_PAGE_LABELS.vsmf05, icon: '05' },
      { key: 'vsmf06', label: APP_PAGE_LABELS.vsmf06, icon: '06' },
      { key: 'vsmf07', label: APP_PAGE_LABELS.vsmf07, icon: '07' },
    ],
  },
  {
    title: 'Module Gamification',
    tone: 'cyan',
    items: [
      { key: 'gsmf01', label: APP_PAGE_LABELS.gsmf01, icon: '01' },
      { key: 'gsmf02', label: APP_PAGE_LABELS.gsmf02, icon: '02' },
      { key: 'gsmf03', label: APP_PAGE_LABELS.gsmf03, icon: '03' },
      { key: 'gsmf04', label: APP_PAGE_LABELS.gsmf04, icon: '04' },
    ],
  },
  {
    title: 'Hệ thống',
    tone: 'cyan',
    items: [
      { key: 'qc-criteria', label: APP_PAGE_LABELS['qc-criteria'], icon: 'QC' },
      { key: 'lecturer-question-bank', label: APP_PAGE_LABELS['lecturer-question-bank'], icon: 'LQ' },
      { key: 'archived-products', label: APP_PAGE_LABELS['archived-products'], icon: 'LT' },
      { key: 'users', label: APP_PAGE_LABELS.users, icon: 'US' },
      { key: 'audit', label: APP_PAGE_LABELS.audit, icon: 'LG' },
    ],
  },
  {
    title: 'Hỗ trợ',
    tone: 'cyan',
    items: [{ key: 'guide', label: APP_PAGE_LABELS.guide, icon: 'HD' }],
  },
];

const APP_ALLOWED_PAGES: Record<RoleKey, PageKey[]> = {
  admin: Object.keys(APP_PAGE_LABELS) as PageKey[],
  pm: [
    'profile',
    'guide',
    'dashboard',
    'tracking',
    'notifications',
    'client-orders',
    'client-order-detail',
    'client-new-order',
    'producer-inbox',
    'order-pm-dashboard',
    'producer-launch',
    'producer-deliver',
    'producer-invoice',
    'production-workflow',
    'schedule-setup',
    'my-tasks',
    'smf01',
    'smf02',
    'vsmf01',
    'vsmf02',
    'gsmf01',
    'gsmf02',
    'archived-products',
  ],
  specialist: ['profile', 'guide', 'notifications', 'my-tasks', 'smf02', 'smf03', 'smf05', 'smf06', 'smf08', 'vsmf02', 'vsmf03', 'vsmf05', 'vsmf06', 'gsmf02', 'gsmf04'],
  qc: ['profile', 'guide', 'notifications', 'my-tasks', 'smf04', 'smf07', 'vsmf04', 'vsmf07', 'gsmf03', 'qc-criteria', 'lecturer-question-bank', 'tracking'],
  client: ['profile', 'guide', 'client-orders', 'client-order-detail', 'client-products', 'client-delivery', 'client-payment', 'notifications'],
  client_director: ['profile', 'guide', 'client-orders', 'client-order-detail', 'client-products', 'client-delivery', 'client-payment', 'client-approvals', 'notifications'],
};

export function getAllowedPagesForRole(role: RoleKey) {
  return APP_ALLOWED_PAGES[role];
}
